### ISSUE TITLE
Typo: Wrong table index in the paper

### ISSUE THREAD

**Issue by Frankie-Dejong** [TencentARC/Divot#2]
Thanks for the great work! I am currently reading the paper on https://arxiv.org/pdf/2412.04432
It seems that it should be `Table 7` instead of `Table 8` here.

![img](https://github.com/user-attachments/assets/c2715b6e-036c-437a-b544-69ca5d5ddaeb)

Cuz it is mentioned as `As listed in Tab. 7, GMM modeling achieves better performance than diffusion modeling and MSE regression in video generation.` in the paper, and there is no `Table 7` either.

**Comment by geyuying** [comment]
Thanks for your suggestion! We will fix this mistake in the updated version.
